apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dockerworkload
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: dockerworkload
spec:
  params:
  - name: dockerfile
    value: ./Dockerfile
  source:
    git:
      url: https://github.com/jkhan24558/tap-docker-workloads
      ref:
        branch: main